package session

import (
	"strings"
	"testing"
)

func TestCleanPromptText(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "empty input",
			input:    "",
			expected: "",
		},
		{
			name:     "plain clean text",
			input:    "fix sessions command working directory",
			expected: "fix sessions command working directory",
		},
		{
			name:     "wrapped in USER_REQUEST",
			input:    "<USER_REQUEST>\nlets pickup the issues opened\n</USER_REQUEST>\n<ADDITIONAL_METADATA>\nThe current local time is: 2026-09-28.\n</ADDITIONAL_METADATA>",
			expected: "lets pickup the issues opened",
		},
		{
			name:     "leading screenshot path",
			input:    "/var/folders/g4/cr6bc0b13_q2kdrkwt3j1l0w0000gn/T/TemporaryItems/NSIRD_screencaptureui_mbPjTm/Screenshot 2026-10-02 at 2.26.50 PM.png it does not show the work dir",
			expected: "it does not show the work dir",
		},
		{
			name:     "claude command caveat wrapper",
			input:    "<local-command-caveat>The command below was generated by Claude</local-command-caveat> git status --short",
			expected: "git status --short",
		},
		{
			name:     "image marker [Image #1]",
			input:    "[Image #1] why is aim getting sig killed?",
			expected: "why is aim getting sig killed?",
		},
		{
			name:     "multiline with extra spaces",
			input:    "   first line\n\n   second line   with   extra   spaces   ",
			expected: "first line second line with extra spaces",
		},
		{
			name:     "summary tag extraction",
			input:    "<summary>Implement session directory and rich preview card</summary>",
			expected: "Implement session directory and rich preview card",
		},
		{
			name:     "preserves valid html tags in code prompt",
			input:    "how to center a <div> element with CSS flexbox?",
			expected: "how to center a <div> element with CSS flexbox?",
		},
		{
			name:     "caps extremely long prompts to 500 characters",
			input:    strings.Repeat("a", 600),
			expected: strings.Repeat("a", 500) + "...",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := CleanPromptText(tc.input)
			if actual != tc.expected {
				t.Errorf("CleanPromptText(%q) = %q; want %q", tc.input, actual, tc.expected)
			}
		})
	}
}
